### ISSUE TITLE
[error] Class org.optaplanner.core.impl.solution.Solution not found

### ISSUE THREAD

**Issue by grogcw** [juanignaciosl/wedding-tables-planner#1]
Hi !

I'm trying to use your code with the new "sbt solution", and new versions of optaplanner and drools-core that are now 7.9.0 instead of 6.0.1 as you compiled in 2014.

I updated the version number in the build.sbt at the root of your code, as the repo seems to no longer have it.

The thing is my outpout to sbt run console after loading my_server_ip:9000 is :

```
[info] Loading project definition from /root/wedding-tables-planner-web/project
[info] Set current project to wedding-tables-planner (in build file:/root/wedding-tables-planner-web/)


Cannot load the JNotify native library (no jnotify in java.library.path)
Play will check file changes for each request, so expect degraded reloading performace.

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 7 Scala sources and 1 Java source to /root/wedding-tables-planner-web/target/scala-2.11/classes...
[warn] Class org.optaplanner.core.impl.solution.Solution not found - continuing with a stub.
[warn] Class org.optaplanner.core.impl.solution.Solution not found - continuing with a stub.
[warn] Class org.optaplanner.core.api.domain.value.ValueRangeProvider not found - continuing with a stub.
[error] Class org.optaplanner.core.impl.solution.Solution not found - continuing with a stub.
[warn] three warnings found
[error] one error found
[error] (compile:compile) Compilation failed
[error] application -

! @78p0dlg2o - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[Class org.optaplanner.core.impl.solution.Solution not found - continuing with a stub.]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:297) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:292) ~[na:na]
[warn] play - No application found at invoker init
```

It seems to the not expert on java/scala/angular that I am, that there is a deprecated class call in your DiningConfiguration.java, line 16.

I might totally be wrong tho.

As the code seems to run through a compiled jar (again, not an expert), I can't touch your source.

Can you see if you can replicate and/or update ?

Thanks for taking care!

PS : JNotify seems to fall too, but it might be on my side and it seems that it's not a stopping point on the process.
PS/2 : The system it's running on is a brand new freshly installed Debian with sbt latest.

**Comment by grogcw** [comment]
I also could reproduce this exact same error on a MacOSX with Oracle JDK8 and brew's sbt & scala.

**Comment by grogcw** [comment]
Turns out I downloaded the jars for Optaplanner 6.0.1 Final and put them in the lib folder at the root of the project and everything except JNotify works, so....case partially closed if you don't want to upgrade your code :)

**Comment by juanignaciosl** [comment]
@grogcw oh, thanks! I've been pretty busy and I haven't been able to stop on this :_). Glad to hear the workaround you found! Leave this open, who knows if I'll be able to fix this eventually :-)
