### ISSUE TITLE
Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @1f3f4916

### ISSUE THREAD

**Issue by cellulosa** [juanignaciosl/wedding-tables-planner#2]
Hi there, I'm trying to use the planner but when I launch it I get the following error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:336)
	at org.optaplanner.core.config.solver.XmlSolverFactory.buildXstream(XmlSolverFactory.java:36)
	at org.optaplanner.core.config.solver.XmlSolverFactory.<init>(XmlSolverFactory.java:46)
	at org.optaplanner.core.config.solver.XmlSolverFactory.<init>(XmlSolverFactory.java:50)
	at com.juanignaciosl.weddingtablesplanner.WeddingTablesPlanner.planTables(WeddingTablesPlanner.java:19)
	at com.juanignaciosl.weddingtablesplanner.WeddingTablesPlanner.main(WeddingTablesPlanner.java:11)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @1f3f4916
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:59)
	... 9 more
```

I'm not really familiar with Java and am just starting to play with Optaplanner, but I guess this has to do with me using newer versions? I'm on `OptaPlanner 8.14.0` and `eclipse-java-2021-09` on MacOS.

**Comment by cellulosa** [comment]
I think I found a solution! For those having the same issue you need to run this with the following parameters:

`--illegal-access=warn --add-opens java.base/java.lang=ALL-UNNAMED`

I still get these errors but at least the resolvers runs...

```
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.collections.TreeMapConverter (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.util.TreeMap.comparator
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.util.Properties.defaults
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.extended.DynamicProxyConverter (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.lang.reflect.Proxy.h
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.text.AttributedCharacterIterator$Attribute.name
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.text.AttributedCharacterIterator$Attribute.instanceMap
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.text.AttributedCharacterIterator$Attribute.serialVersionUID
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.awt.font.TextAttribute.instanceMap
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.awt.font.TextAttribute.serialVersionUID
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.AbstractAttributedCharacterIteratorAttributeConverter (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to method java.text.AttributedCharacterIterator$Attribute.getName()
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.enums.EnumSetConverter (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.util.EnumSet.elementType
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.enums.EnumMapConverter (file:/Users/cellulosa/.m2/repository/com/thoughtworks/xstream/xstream/1.4.3/xstream-1.4.3.jar) to field java.util.EnumMap.keyType
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by juanignaciosl** [comment]
Hi! I'm afraid that I did this 8 years ago and it was my last Java project, so I'm afraid I can't help :sweat_smile: . But thank you for the self-response!
